### ISSUE TITLE
Working with Kaminari

### ISSUE THREAD

**Issue by danieldocki** [endofunky/oprah#10]
How do I make Oprah work with Kaminari?

**Comment by endofunky** [comment]
Do you have any issue in particular?

**Comment by endofunky** [comment]
I assume this is resolved, so closing this issue.

**Comment by danieldocki** [comment]
Sorry for delay...

when used this:

```
events = present_many(Event.page(params[:page]))
```

got this error in view

```
undefined method `total_pages' for #<Array:0x007f9d07347ed8>
```
