### ISSUE TITLE
Minor Refactoring

### ISSUE THREAD

**Issue by RichardWigley** [endofunky/oprah#6]
Hello endoffunky

I wanted to add a minor refactoring to your codebase using Kernal#Array and a Self assignment.

````
-     presenters = presenters & (only.kind_of?(Array) ? only : [only]) if only
+    presenters &= Array(only) if only
````

[Git commit](https://github.com/RichardWigley/oprah/commit/488cdaaf0d8533a3efa3875bf144204bc1fc11ce)

Look good?

**Comment by endofunky** [comment]
Heh, this is quite _golfy_, but sure, feel free to send a pull request.

**Comment by RichardWigley** [comment]
Thanks eof, I've had fun reading through your code - It's very clean and was enjoying it.
